export default function PrivacyPage() {
  return (
    <div className="relative min-h-screen flex flex-col bg-gradient-to-br from-[#0a232e] to-[#08222b]">
      <div className="fixed inset-0 z-[-1] bg-gradient-to-br from-[#0a0a0a] via-[#1a1a1a] to-blue-900 opacity-80 backdrop-blur-xl" aria-hidden="true" />
      <div className="relative z-10 w-full flex flex-col pt-15">
        <div className="container mx-auto max-w-4xl px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16">
          <div className="bg-white/5 backdrop-blur-sm rounded-2xl p-6 sm:p-8 md:p-10 border border-white/10">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-blue-500 mb-8">Privacy Policy</h1>
            <p className="text-gray-300 mb-8">Last updated: January 15, 2025</p>
            
            <div className="space-y-6 text-gray-300">
              <p>
                This <span className="text-white font-semibold">Privacy Policy</span> describes our policies and procedures on the collection, use, and disclosure of your information when you use the <span className="text-white font-semibold">Service</span> and informs you about your privacy rights and how <span className="text-white font-semibold">Indian law</span> protects you.
              </p>

              <p>
                We use your <span className="text-white font-semibold">personal data</span> to provide and improve the <span className="text-white font-semibold">Service</span>. By using the Service, you agree to the collection and use of information in accordance with this <span className="text-white font-semibold">Privacy Policy</span>.
              </p>

              <p>
                This policy is prepared in accordance with the <span className="text-white font-semibold">Digital Personal Data Protection Act, 2023</span> (India) and other applicable Indian laws.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Interpretation and Definitions</h2>
              <p>
                Words with capitalized initial letters have meanings defined under the conditions below. These definitions apply whether the terms appear in singular or plural.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Definitions</h3>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>Account:</strong> A unique account created for you to access our Service.</li>
                <li><strong>Company:</strong> Refers to <span className="text-white font-semibold">Sagar Edits</span>, GTB Nagar, Delhi - 110009, India.</li>
                <li><strong>Country:</strong> Refers to <span className="text-white font-semibold">India</span>.</li>
                <li><strong>Device:</strong> Any device that can access the Service.</li>
                <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> Refers to the website accessible at <span className="text-white font-semibold">https://sagaredits.in</span>.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service.</li>
                <li><strong>Website:</strong> <span className="text-white font-semibold">Sagar Edits</span> (<span className="text-white font-semibold">https://sagaredits.in</span>)</li>
                <li><strong>You:</strong> The individual or legal entity accessing the Service.</li>
              </ul>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Collecting and Using Your Personal Data</h2>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Types of Data Collected</h3>
              <p className="mb-4">We may ask for information that can be used to contact or identify you, including:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>Name</li>
                <li>Email address</li>
                <li>Platform (Instagram, YouTube, etc.)</li>
                <li>Company/Brand</li>
                <li>Campaign Type</li>
                <li>Campaign Description</li>
                <li><span className="text-white font-semibold">Usage Data</span></li>
              </ul>
              <p className="mb-4">We do not collect financial data or government-issued ID.</p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Usage Data</h3>
              <p>
                <span className="text-white font-semibold">Usage Data</span> may include information such as your device's IP address, browser type, pages visited, time spent, and diagnostic data.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Information from Third-Party Social Media Services</h3>
              <p>
                If you log in via platforms like Google, Facebook, or LinkedIn, we may collect associated data such as your name, email, and contact list.
              </p>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Tracking Technologies and Cookies</h3>
              <p>
                We use <span className="text-white font-semibold">cookies</span> and similar technologies to enhance your experience. You can disable cookies via browser settings.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Use of Your Personal Data</h2>
              <p className="mb-4">We use your data to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>Respond to your campaign inquiries</li>
                <li>Improve our website and services</li>
                <li>Send important updates</li>
                <li>Send promotional content only if you have opted in</li>
              </ul>
              <p>
                You may opt out of promotional messages anytime.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Retention of Your Personal Data</h2>
              <p>
                We retain your data as long as necessary or required by <span className="text-white font-semibold">Indian law</span>.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Transfer of Your Personal Data</h2>
              <p>
                Your data may be processed on servers in India or overseas, compliant with Indian data protection regulations.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Delete Your Personal Data</h2>
              <p>
                You may request deletion anytime. Some data may be retained as per legal requirements.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Disclosure of Your Personal Data</h2>
              <p className="mb-4">We may disclose data:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>To service providers</li>
                <li>For business transfers</li>
                <li>To comply with legal obligations</li>
                <li>To protect users or enforce our policies</li>
              </ul>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Security of Your Personal Data</h2>
              <p>
                We use reasonable security measures, but no method is completely secure.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Children's Privacy</h2>
              <p>
                Our Service is not for individuals under 18. Contact us if your child has submitted data.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Links to Other Websites</h2>
              <p>
                We are not responsible for privacy practices of third-party websites linked from our Service.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Changes to This Privacy Policy</h2>
              <p>
                We may update this policy and notify users via email or website.
              </p>

              <h2 className="text-2xl font-bold text-white mt-8 mb-4">Contact Us</h2>
              <p className="mb-4">
                For any privacy questions or data access/deletion requests, contact:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-6">
                <li>📧 Email: contactsagaredits@gmail.com</li>
                <li>🌐 Website: https://www.sagaredits.in/contact</li>
              </ul>

              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Grievance Officer (as per Indian IT Rules, 2021)</h3>
              <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                <p className="font-semibold text-white mb-2">Grievance Officer</p>
                <p className="mb-1">Name: Sagar Singh</p>
  <p className="mb-1">
    Email:&nbsp;  
    <a 
      href="mailto:contactsagaredits@gmail.com" 
      className="text-blue-400 hover:underline"
    >
      contactsagaredits@gmail.com
    </a>
  </p>
  <p>Address: GTB Nagar, Delhi - 110009, India</p>
              </div>
              <p className="mt-4">
                You may contact the <span className="text-white font-semibold">Grievance Officer</span> regarding any concerns or complaints.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}